=== AdityaGuzzu/WebDev/SEM6/XML/DTD/ipl/definition.dtd
<!ELEMENT ipl (team+)>
<!ELEMENT team (teamname, homeground, captain, trophies)>
<!ELEMENT teamname (#PCDATA)>
<!ELEMENT homeground (#PCDATA)>
<!ELEMENT captain (#PCDATA)>
<!ELEMENT trophies (#PCDATA)>

=== AdityaGuzzu/WebDev/SEM6/XML/DTD/ipl/teams.xml
<!DOCTYPE ipl SYSTEM "definition.dtd">
<ipl>
    <team>
        <teamname>Sunrisers Hyderabad</teamname>
        <homeground>Hyderabad</homeground>
        <captain>Pat Cumins</captain>
        <trophies>2</trophies>
    </team>
    <team>
        <teamname>Chennai Super Kings</teamname>
        <homeground>Chennai</homeground>
        <captain>MS Dhoni</captain>
        <trophies>5</trophies>
    </team>
</ipl>
